### ISSUE TITLE
npm run dev安装出现错误, 尝试了好多方法没有解决,希望能帮助一下

### ISSUE THREAD

**Issue by wwmin** [Mrjeff578575/Vue-demo-jianshu#1]
npm install 安装一切正常,但是就是在npm run dev时出现了问题:
`
D:\work\Vue\Vue-demo-jianshu>npm run dev

> vue-demo@1.0.0 dev D:\work\Vue\Vue-demo-jianshu
> node build/dev-server.js

module.js:442
    throw err;
    ^

Error: Cannot find module 'D:\work\Vue\Vue-demo-jianshu\build\dev-server.js'
    at Function.Module._resolveFilename (module.js:440:15)
    at Function.Module._load (module.js:388:25)
    at Function.Module.runMain (module.js:575:10)
    at startup (node.js:160:18)
    at node.js:449:3

npm ERR! Windows_NT 10.0.10586
npm ERR! argv "D:\Program Files\nodejs\node.exe" "D:\Program Files\nodejs\node_global\node_modules\npm\bin\npm-cli.js" "run" "dev"
npm ERR! node v6.2.0
npm ERR! npm  v3.10.6
npm ERR! code ELIFECYCLE
npm ERR! vue-demo@1.0.0 dev: `node build/dev-server.js`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the vue-demo@1.0.0 dev script 'node build/dev-server.js'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the vue-demo package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node build/dev-server.js
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs vue-demo
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls vue-demo
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     D:\work\Vue\Vue-demo-jianshu\npm-debug.log
`
希望作者能帮助分析一下我的错误

**Comment by Mrjeff578575** [comment]
你的build文件夹下缺少dev-server.js文件。

**Comment by wwmin** [comment]
@Mrjeff578575 build/dev-server.js不应该是在npm run dev/build时候生成的吗? 求教了.

**Comment by Mrjeff578575** [comment]
是在配置webpack的热加载功能的时候生成的
